name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker Compose Images
      run: |
        docker-compose -f docker-compose.yaml build


    - name: Push Medusa Docker image
      run: |
        docker-compose -f docker-compose.yaml push

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin
 
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project firm-amp-429105-j1
        kubectl apply -f dataredis.yaml --validate=false
        kubectl apply -f datapostgres.yaml --validate=false
        kubectl apply -f deployement.yaml --validate=false
        kubectl get services 
        